export const RARITY = {
  Common: { label: 'สามัญ', color: 'text-parchment/60 border-dim/40', weight: 40 },
  Uncommon: { label: 'ไม่สามัญ', color: 'text-green-400/80 border-green-800/40', weight: 25 },
  Rare: { label: 'หายาก', color: 'text-gold border-gold/40', weight: 15 },
  Legendary: { label: 'ในตำนาน', color: 'text-red-400 border-blood/50', weight: 5 },
}

export const GHOSTS = [
  // ── เร่ร่อน ──────────────────────────────────────────
  {
    id: 'STL-GH-001',
    nameTh: 'ผีตายโหง',
    class: 'เร่ร่อน',
    rarity: 'Common',
    dangerLevel: 2,
    description: 'วิญญาณผู้เสียชีวิตกะทันหันจากอุบัติเหตุหรือความรุนแรง',
    fieldNote: 'ลักษณะ: เงาราง ๆ ของร่างมนุษย์ สูงประมาณ 150–170 ซม. มักก้มหน้า เดินโซเซช้า ๆ โดยไม่มีเสียงฝีเท้า บางครั้งมีรอยเลือดหรือบาดแผลที่เห็นชัดเจน ปรากฏในพื้นที่เกิดอุบัติเหตุหรือสถานที่ร้าง\nหมายเหตุ: ผู้พบเห็นควรหลีกเลี่ยงการติดตามหรือเรียกชื่อ',
    coexistTip: 'หลีกเลี่ยงการอยู่คนเดียวในที่มืด ติดตั้งแสงสว่างให้เพียงพอ',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: torn ragged dark white Thai clothing with dark stains, no visible face (head bowed and hair covering), slow walking posture with arms hanging limp, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['accident_site', 'road', 'hospital'], timeBonus: 0.1, rainy: false },
    icon: '🕴',
  },
  {
    id: 'STL-GH-002',
    nameTh: 'ผีหัวขาด',
    class: 'เร่ร่อน',
    rarity: 'Uncommon',
    dangerLevel: 3,
    description: 'ร่างไร้ศีรษะเดินโซเซ มือข้างหนึ่งถือหัวตัวเอง เกิดจากการประหารหรือตายอย่างทารุณ',
    fieldNote: 'ลักษณะ: ร่างกายมนุษย์เดินโซเซโดยไม่มีศีรษะ มือข้างหนึ่งถือหัวตัวเองไว้ เลือดไหลซึมเล็กน้อย มักพบตามถนนสายเก่า\nหมายเหตุ: ห้ามถ่ายภาพใกล้ชิด อาจก่อให้เกิดอาการวิงเวียนตามมา',
    coexistTip: 'หลีกเลี่ยงถนนร้างในยามดึก อย่ามองตรงในทิศทางที่ปรากฏ',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: dark muted Thai farmer clothing, headless body with a detached head cradled in one lowered hand, no visible face (head held at side with long hair obscuring), staggering unsteady stance, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['road', 'historic'], timeBonus: 0.15 },
    icon: '👻',
  },
  {
    id: 'STL-GH-003',
    nameTh: 'ผีเปรต',
    class: 'เร่ร่อน',
    rarity: 'Rare',
    dangerLevel: 4,
    description: 'ร่างสูงผอม ปากรูเข็ม มือใหญ่ ไฟลุกบนศีรษะ ทุกข์ทรมานจากกรรมเก่า',
    fieldNote: 'ลักษณะ: สูงผิดปกติ ผอมแห้ง ปากเล็กเหมือนรูเข็ม มือใหญ่เกินสัดส่วน มีไฟลุกอยู่บริเวณศีรษะ ปรากฏตามสถานที่ที่มีการทำบุญหรือวัด\nหมายเหตุ: ตรวจพบช่วงเข้าพรรษา อย่าแสดงความรังเกียจ',
    coexistTip: 'ทำบุญอุทิศส่วนกุศลให้แก่ผู้ล่วงลับ จะลดการปรากฏตัว',
    inpaintingPrompt: 'A photorealistic dark silhouette: an impossibly tall gaunt figure — only the lower two-thirds of the body visible, torso and above cut off by the top of the frame. Extremely thin dark legs, oversized bony hands dangling at mid-frame, shreds of dark loincloth, faint smoldering glow visible at the very top edge of frame. Off-center, naturally present in this scene, matching the lighting direction and intensity of the original photo, seamlessly integrated, cinematic dark atmospheric photography, 35mm film grain, subtle',
    spawnConditions: { locationTypes: ['temple', 'cemetery'], timeBonus: 0.2 },
    icon: '🔥',
  },
  {
    id: 'STL-GH-004',
    nameTh: 'ผีโขมด',
    class: 'เร่ร่อน',
    rarity: 'Legendary',
    dangerLevel: 5,
    description: 'ดวงไฟลอยนำทางหลอกให้หลงป่าหรือหลงทาง วิญญาณคนตายในที่ชุ่มน้ำ',
    fieldNote: 'ลักษณะ: ดวงไฟสีส้มอ่อนลอยระดับสายตา เคลื่อนที่ไม่แน่นอน มักปรากฏในทุ่งนาหรือป่าชื้น ล่อให้เหยื่อเดินตาม\nหมายเหตุ: ห้ามเดินตามดวงไฟที่ไม่ทราบที่มาในเวลากลางคืนโดยเด็ดขาด',
    coexistTip: 'หากพบให้หยุดนิ่ง ไม่ตามดวงไฟ รอจนดวงไฟดับไปเอง',
    inpaintingPrompt: 'A photorealistic atmospheric glowing orb of orange-white light floating at eye level, will-o-wisp form, pulsing warm glow casting subtle light on nearby surfaces, no physical body, naturally present in the scene off-center as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['field', 'wetland', 'natural_feature'], timeBonus: 0.3, nightOnly: true },
    icon: '🔮',
  },

  // ── ป่า ──────────────────────────────────────────────
  {
    id: 'STL-GH-005',
    nameTh: 'ผีกองกอย',
    class: 'ป่า',
    rarity: 'Common',
    dangerLevel: 2,
    description: 'ผีขาเดียว เขย่งเดินดัง "เก็งกอย" ชอบดูดเลือดหัวแม่เท้าของคนนอนในป่า',
    fieldNote: 'ลักษณะ: ร่างมีขาข้างเดียว เขย่งเดินดัง "เก็งกอย" ปากเป็นท่อเล็ก ๆ ชอบดูดเลือดหัวแม่เท้า\nหมายเหตุ: นอนตะแคงให้เท้าซุกไว้ใต้ผ้าห่มหากพักแรมในป่า',
    coexistTip: 'ห้ามนอนหงายให้เท้าชี้ออกนอกเต็นท์ ใส่ถุงเท้าหนาตลอดคืน',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: dark ragged forest clothing, single leg with no knee joint tapering to a point, no visible face (hair and shadow covering), hopping posture with arms extended for balance, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['park', 'forest', 'natural_feature'], timeBonus: 0.1 },
    icon: '🦵',
  },
  {
    id: 'STL-GH-006',
    nameTh: 'ผีด้ง',
    class: 'ป่า',
    rarity: 'Uncommon',
    dangerLevel: 3,
    description: 'ผีร้ายในป่าลึก ชอบล่อพรานหรือคนเดินป่าให้หลงทาง',
    fieldNote: 'ลักษณะ: เงาทึบรูปร่างคล้ายมนุษย์ แต่สูงใหญ่ผิดสัดส่วน เดินเงียบในป่าทึบ ปล่อยเสียงหลอกล่อ\nหมายเหตุ: ห้ามตอบรับเสียงเรียกในป่าหากไม่แน่ใจว่าเป็นมนุษย์',
    coexistTip: 'ก่อนเข้าป่าให้ขออนุญาตเจ้าป่า นำผ้ายันต์หรือของขลังติดตัว',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: dark earth-toned wild tattered clothing on an oversized 2-meter humanoid form, hunched shoulders and thick limbs, no visible face (deep shadow), threatening looming posture casting shadow on floor, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['park', 'forest', 'natural_feature'], timeBonus: 0.1 },
    icon: '🌲',
  },
  {
    id: 'STL-GH-007',
    nameTh: 'นางตะเคียน',
    class: 'ป่า',
    rarity: 'Uncommon',
    dangerLevel: 2,
    description: 'หญิงงามในชุดไทยโบราณ สิงสถิตในต้นตะเคียนใหญ่ หวงถิ่นฐาน',
    fieldNote: 'ลักษณะ: หญิงงามผมยาวดำสนิท ผิวขาวซีด สวมชุดไทยโบราณ ยืนสงบนิ่งใกล้ต้นตะเคียน มักทำให้บริเวณรอบ ๆ สะอาดผิดปกติ\nหมายเหตุ: อย่าเข้าไปรบกวน ห้ามตัดต้นไม้ใกล้เคียง',
    coexistTip: 'แสดงความเคารพต่อต้นไม้ใหญ่ ไม่ทิ้งขยะในบริเวณใกล้เคียง',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: dark elegant traditional Thai sabai and chong kraben with subtle gold trim, no visible face (long straight black hair completely covering face and falling past waist), graceful poised upright stance with hands at sides, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['park', 'forest', 'natural_feature'], timeBonus: 0.05 },
    icon: '🌳',
  },
  {
    id: 'STL-GH-008',
    nameTh: 'นางตานี',
    class: 'ป่า',
    rarity: 'Rare',
    dangerLevel: 3,
    description: 'หญิงสาวผมยาวหอมกลิ่นกล้วย สิงในต้นกล้วยตานีตายพราย มักปรากฏคืนพระจันทร์เต็มดวง',
    fieldNote: 'ลักษณะ: หญิงสาวผมยาวหอมกลิ่นกล้วย ฝ่ามือและฝ่าเท้าแดงอ่อน ริมฝีปากสีแดงสด ปรากฏใกล้ต้นกล้วยตานีในคืนพระจันทร์เต็มดวง\nหมายเหตุ: หลีกเลี่ยงการเดินคนเดียวในพื้นที่กล้วยป่า',
    coexistTip: 'ห้ามปัสสาวะใต้ต้นกล้วยในยามค่ำคืน หากพบให้แสดงความเคารพแล้วถอยออก',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: dark green-toned traditional Thai dress, no visible face (very long black hair parted in center covering most of face), red palms visible at sides, faint red lips just barely visible through hair, standing still and upright, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['park', 'garden', 'natural_feature'], timeBonus: 0.15, fullMoon: true },
    icon: '🌙',
  },

  // ── น้ำ ──────────────────────────────────────────────
  {
    id: 'STL-GH-009',
    nameTh: 'ผีพราย',
    class: 'น้ำ',
    rarity: 'Common',
    dangerLevel: 3,
    description: 'หญิงในชุดขาวลอยตัวเหนือผิวน้ำ ผมยาวเปียกชุ่ม มักล่อให้คนเข้าไปใกล้',
    fieldNote: 'ลักษณะ: หญิงในชุดขาวลอยตัวหรือยืนที่ขอบคลอง ผมยาวเปียกชุ่ม ปรากฏหลังฝนตกหนัก\nหมายเหตุ: ห้ามตามเสียงเรียกหรือลงน้ำในเวลากลางคืน',
    coexistTip: 'ไม่ว่ายน้ำคนเดียวหลังพระอาทิตย์ตก อย่าชี้นิ้วไปยังผิวน้ำโดยไม่จำเป็น',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: white traditional Thai dress soaking wet and clinging to body, no visible face (long wet black hair plastered over entire face), arms hanging limp at sides with water dripping from fingertips, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['river', 'canal', 'water'], rainyBonus: true, timeBonus: 0.1 },
    icon: '💧',
  },
  {
    id: 'STL-GH-010',
    nameTh: 'ผีโป่งน้ำ',
    class: 'น้ำ',
    rarity: 'Uncommon',
    dangerLevel: 2,
    description: 'วิญญาณสัตว์หรือคนที่ตายในน้ำโป่ง ปรากฏเป็นร่างลอยตามผิวน้ำ',
    fieldNote: 'ลักษณะ: ร่างมนุษย์หรือสัตว์ลอยตามผิวน้ำอย่างเงียบสงบ เคลื่อนที่สวนทางกระแสน้ำ\nหมายเหตุ: อย่าสัมผัสน้ำที่มีฟองผิดปกติในยามกลางคืน',
    coexistTip: 'หลีกเลี่ยงแหล่งน้ำนิ่งในป่าที่ไม่คุ้นเคย',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: pale waterlogged tattered traditional Thai clothing, no visible face (face down or bloated and in deep shadow), floating horizontal posture slightly above ground as if still on water surface, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['river', 'canal', 'water', 'natural_feature'], rainyBonus: true },
    icon: '🌊',
  },
  {
    id: 'STL-GH-011',
    nameTh: 'นางน้ำหลวง',
    class: 'น้ำ',
    rarity: 'Rare',
    dangerLevel: 4,
    description: 'วิญญาณหญิงที่จมน้ำสิงสถิตในแหล่งน้ำลึก ปกครองอาณาเขตใต้น้ำ',
    fieldNote: 'ลักษณะ: หญิงงามในชุดไทยโบราณสีน้ำเงินเข้ม ลอยอยู่กลางน้ำลึก เส้นผมลอยพัดไปมา\nหมายเหตุ: แหล่งน้ำที่ตรวจพบไม่ควรว่ายน้ำเป็นระยะเวลา 7 วัน',
    coexistTip: 'ถ้าต้องข้ามแม่น้ำในเวลากลางคืน ให้อธิษฐานขออนุญาตก่อนเสมอ',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: dark deep-blue traditional Thai court dress with gold trim, no visible face (long black hair flowing upward as if underwater, obscuring face), arms extended slightly as if weightless, floating posture, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['river', 'lake', 'water'], timeBonus: 0.2 },
    icon: '🏞',
  },
  {
    id: 'STL-GH-012',
    nameTh: 'แม่นาคพระโขนง',
    class: 'น้ำ',
    rarity: 'Legendary',
    dangerLevel: 5,
    description: 'หญิงตั้งครรภ์ในชุดขาว ผมยาว ปรากฏใกล้บ้านร้างหรือคลอง',
    fieldNote: 'ลักษณะ: หญิงตั้งครรภ์ในชุดขาว ผมยาวดำ หน้าท้องโต ใบหน้าสงบแต่แฝงความเศร้าโศก มักปรากฏใกล้คลองพระโขนงหรือสถานที่ที่มีความเชื่อมโยงกับการเสียชีวิตในการคลอดบุตร\nหมายเหตุ: พื้นที่นี้มีความเสี่ยงสูง ควรรายงานศูนย์ปฏิบัติการทันที',
    coexistTip: 'ห้ามพูดชื่อดัง ๆ ในพื้นที่ใกล้เคียง รีบออกจากพื้นที่โดยทันที',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: white traditional Thai sabai dress, large visibly pregnant belly, no visible face (long straight black hair falling over face), arms resting gently on belly, standing very still, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['canal', 'water', 'old_house'], timeBonus: 0.3, nightOnly: true },
    icon: '👘',
  },

  // ── อาคม ──────────────────────────────────────────────
  {
    id: 'STL-GH-013',
    nameTh: 'กระหัง',
    class: 'อาคม',
    rarity: 'Uncommon',
    dangerLevel: 3,
    description: 'ผู้ชายใช้กระด้งเป็นปีก สากตำข้าวเป็นหาง บินหากินของเน่าในยามค่ำ',
    fieldNote: 'ลักษณะ: ร่างผู้ชายบินโดยใช้กระด้งเป็นปีก สากตำข้าวเป็นหาง ผ้าโจงกระเบนสีเข้ม มักปรากฏใกล้กองขยะหรือของเน่าเสีย\nหมายเหตุ: หากเห็นสิ่งของบินได้ในเวลากลางคืนให้รายงานทันที',
    coexistTip: 'ปิดฝาภาชนะอาหารให้แน่นในเวลากลางคืน ติดตะแกรงหน้าต่างให้ทุกบาน',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: dark pha chung kraben traditional cloth, arms spread wide gripping a large round woven winnowing basket as wings, rice pestle visible as tail, no visible face (in shadow, head raised looking upward), mid-flight floating posture, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['residential', 'rural'], timeBonus: 0.15 },
    icon: '🦅',
  },
  {
    id: 'STL-GH-014',
    nameTh: 'ปอบ',
    class: 'อาคม',
    rarity: 'Rare',
    dangerLevel: 4,
    description: 'ผีที่กินของดิบในร่างมนุษย์ เกิดจากผู้เล่นอาคมผิดข้อห้าม',
    fieldNote: 'ลักษณะ: ปรากฏในร่างมนุษย์ปกติแต่มีดวงตาแวววาวในที่มืด ชอบกินอวัยวะภายในสดของสัตว์ บางครั้งสิงร่างผู้อื่น\nหมายเหตุ: ยากต่อการตรวจพบด้วยตาเปล่า ต้องอาศัยเครื่องมือพิเศษของส.ต.ล.',
    coexistTip: 'หากสงสัยว่ามีปอบในบริเวณใกล้เคียง ให้นำกระเทียมและน้ำมนต์ประพรมรอบบ้าน',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: ragged dark peasant clothing, crouching predatory low posture, no visible face (only two faintly glowing yellow eyes visible through shadow), hands outstretched with clawed fingers, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['residential', 'rural', 'temple'], timeBonus: 0.2 },
    icon: '😱',
  },
  {
    id: 'STL-GH-015',
    nameTh: 'กระสือ',
    class: 'อาคม',
    rarity: 'Rare',
    dangerLevel: 4,
    description: 'หัวผู้หญิงลอยพร้อมไส้พุงยาว ดวงไฟสีเขียว บินหากินของคาว',
    fieldNote: 'ลักษณะ: หัวผู้หญิงลอยพร้อมอวัยวะภายในห้อยยาว ดวงตาเรืองแสงสีเขียว มีแสงสีเขียวล้อมรอบ มักบินหากินในเวลากลางคืน\nหมายเหตุ: อย่าเปิดเผยตำแหน่งที่พบต่อสาธารณะ',
    coexistTip: 'ปิดหน้าต่างและประตูให้แน่นตลอดคืน นำกิ่งหนามหรือของมีคมวางไว้หน้าประตู',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette: disembodied woman\'s head with long black hair floating mid-air, long dark gossamer wisps trailing below faintly glowing green, no body, naturally present in the scene off-center as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['residential', 'rural', 'temple', 'cemetery'], timeBonus: 0.25, nightOnly: true },
    icon: '👁',
  },
  {
    id: 'STL-GH-016',
    nameTh: 'ผีเบื้อ',
    class: 'อาคม',
    rarity: 'Legendary',
    dangerLevel: 5,
    description: 'ผีจากคาถาโบราณที่ร้ายกาจที่สุด ควบคุมยาก เกิดจากอาคมผิดพลาดร้ายแรง',
    fieldNote: 'ลักษณะ: ร่างขนาดใหญ่ผิดปกติ ตาสีแดง กรงเล็บยาว ส่งเสียงดังน่ากลัว บางครั้งปรากฏเป็นหลายร่างพร้อมกัน\nหมายเหตุ: ห้ามเข้าใกล้โดยเด็ดขาด รอทีมปฏิบัติการพิเศษ',
    coexistTip: 'ถอยออกจากพื้นที่ทันที ติดต่อส.ต.ล.ฉุกเฉิน ห้ามมองตาโดยตรง',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: enormous dark hulking figure twice human height in ancient ritual tattered robes, no visible face (deep shadow with only two red glowing eyes), long curved claws on both hands, dark smoky wisp at feet, imposing presence, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['temple', 'cemetery', 'ruin'], timeBonus: 0.35, nightOnly: true },
    icon: '👹',
  },

  // ── โบราณ ──────────────────────────────────────────────
  {
    id: 'STL-GH-017',
    nameTh: 'ผีเด็กหอ',
    class: 'โบราณ',
    rarity: 'Common',
    dangerLevel: 2,
    description: 'วิญญาณเด็กหรือคนรับใช้ในบ้านโบราณ ปรากฏตามห้องร้างในอาคารเก่า',
    fieldNote: 'ลักษณะ: เด็กหรือคนรับใช้ในชุดไทยโบราณ ยืนหรือนั่งเงียบในมุมห้อง มักได้ยินเสียงเดินเล็ก ๆ ในเวลากลางคืน\nหมายเหตุ: ไม่เป็นอันตราย แต่อาจทำให้เกิดอาการหวาดกลัว',
    coexistTip: 'แสดงความเคารพต่ออาคารโบราณ ไม่ทำลายสิ่งของในบริเวณ',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: small child-height figure in pale ancient Thai house-servant clothing, no visible face (head down with dark hair covering, in corner shadow), standing very still with arms at sides, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['old_building', 'historic', 'university'], timeBonus: 0.1 },
    icon: '👦',
  },
  {
    id: 'STL-GH-018',
    nameTh: 'ผีตาโขน',
    class: 'โบราณ',
    rarity: 'Uncommon',
    dangerLevel: 2,
    description: 'วิญญาณจากพิธีตาโขนหรือหน้ากากโบราณ ปรากฏในสถานที่ประกอบพิธีกรรม',
    fieldNote: 'ลักษณะ: ร่างในชุดพิธีกรรมสีสันฉูดฉาด ถือหน้ากากตาโขนขนาดใหญ่ เต้นรำอย่างช้า ๆ ในเวลากลางคืน\nหมายเหตุ: พบบ่อยในช่วงเทศกาลบุญหลวงหรือพิธีกรรมโบราณ',
    coexistTip: 'ไม่รบกวนพิธีกรรมโบราณ แสดงความเคารพต่อประเพณีท้องถิ่น',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: colorful patchwork Thai festival ceremonial costume with a large carved painted wooden mask completely covering the face, slow ritual dance posture with one arm raised, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['temple', 'historic', 'park'], timeBonus: 0.1 },
    icon: '🎭',
  },
  {
    id: 'STL-GH-019',
    nameTh: 'ผีหลังกลวง',
    class: 'โบราณ',
    rarity: 'Rare',
    dangerLevel: 3,
    description: 'ผีที่มีหลังเป็นโพรง เกิดจากคนตายในสถานที่เก่าแก่ที่ถูกทอดทิ้ง',
    fieldNote: 'ลักษณะ: หน้าตาปกติแต่ด้านหลังเป็นโพรงกลวงเหมือนเปลือก มักปรากฏตามทางเดินในอาคารเก่า\nหมายเหตุ: อย่าพยายามมองด้านหลังสิ่งที่สงสัย',
    coexistTip: 'อย่าเดินตามสิ่งที่ไม่คุ้นเคยในอาคารร้าง สังเกตเงาหลังสิ่งที่พบเห็น',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: plain dark traditional Thai clothing viewed from behind showing a completely hollow void where the back and body interior should be, like an empty shell, no visible face (viewed from behind), naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['old_building', 'ruin', 'historic'], timeBonus: 0.15 },
    icon: '🏚',
  },
  {
    id: 'STL-GH-020',
    nameTh: 'ผีต้นโพธิ์',
    class: 'โบราณ',
    rarity: 'Uncommon',
    dangerLevel: 2,
    description: 'วิญญาณสิงต้นโพธิ์ในวัดร้าง ปกปักรักษาต้นไม้ศักดิ์สิทธิ์',
    fieldNote: 'ลักษณะ: เงาทึบปรากฏรอบต้นโพธิ์ใหญ่ในวัดร้าง มักได้ยินเสียงใบไม้ไหวโดยไม่มีลม\nหมายเหตุ: ไม่เป็นอันตรายหากไม่รบกวน',
    coexistTip: 'ห้ามตัดกิ่งหรือเด็ดใบโพธิ์ในวัดร้าง ควรนำดอกไม้ธูปเทียนมาบูชา',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: ancient dark Buddhist monk robes with bark-like texture on exposed hands and forearms, gnarled root-like fingers, no visible face (deep cowl hood casting total shadow on face), standing very still with hands clasped, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['temple', 'historic', 'park'], timeBonus: 0.1 },
    icon: '🌿',
  },

  // ── ราชสำนัก ──────────────────────────────────────────────
  {
    id: 'STL-GH-021',
    nameTh: 'นางรำราชสำนัก',
    class: 'ราชสำนัก',
    rarity: 'Uncommon',
    dangerLevel: 2,
    description: 'วิญญาณนางรำที่ตายอย่างไม่เป็นธรรม ยังเต้นรำในยามค่ำคืน',
    fieldNote: 'ลักษณะ: หญิงในชุดราชสำนักประดับทองเต้นรำอยู่คนเดียวในพื้นที่ว่างเปล่า เสียงดนตรีเบา ๆ แว่วมาโดยไม่ทราบที่มา\nหมายเหตุ: ไม่เป็นอันตรายหากไม่รบกวนการแสดง',
    coexistTip: 'หากได้ยินเสียงดนตรีในสถานที่เก่าแก่ ให้แสดงความเคารพแล้วเดินออก',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: elaborate golden Thai classical dance costume with tall pointed crown and layered jewelry, no visible face (head turned aside in dance pose with crown and shadow obscuring), curved graceful fingers mid-dance, one leg raised in traditional dance posture, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['historic', 'palace', 'museum'], timeBonus: 0.1 },
    icon: '💃',
  },
  {
    id: 'STL-GH-022',
    nameTh: 'ขุนนางตายโหง',
    class: 'ราชสำนัก',
    rarity: 'Rare',
    dangerLevel: 3,
    description: 'ขุนนางที่ถูกประหาร ยังคงเดินตรวจตราในชุดราชสำนักยามค่ำ',
    fieldNote: 'ลักษณะ: ชายในชุดขุนนางโบราณถือตราอาญาสิทธิ์ เดินตรวจตราพื้นที่อย่างเป็นระเบียบ บาดแผลที่คอหรือหน้าอกมองเห็นชัด\nหมายเหตุ: อย่ากีดขวางเส้นทางที่สิ่งนี้เดินผ่าน',
    coexistTip: 'แสดงความเคารพสูงสุด ก้มหัวและให้ทางโดยทันที',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: formal ancient Thai court official costume with ceremonial hat, embroidered jacket and chong kraben, holding a ceremonial baton, no visible face (ceremonial hat brim and shadow covering), upright formal patrol walking posture, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['historic', 'palace', 'government'], timeBonus: 0.2 },
    icon: '⚔️',
  },
  {
    id: 'STL-GH-023',
    nameTh: 'ผีราชินี',
    class: 'ราชสำนัก',
    rarity: 'Legendary',
    dangerLevel: 4,
    description: 'หญิงในชุดราชสำนักโบราณ ผมทรงสูง ประดับเครื่องประดับเก่า ปรากฏในวังร้าง',
    fieldNote: 'ลักษณะ: หญิงในชุดราชสำนักที่หรูหราอย่างยิ่ง ผมทรงสูงประดับเครื่องทอง ผิวซีดสง่างาม ดวงตาว่างเปล่า ปรากฏตามวังเก่าหรือสถานที่ราชสำนักโบราณ\nหมายเหตุ: ระดับอันตรายสูง ต้องรายงานศูนย์ปฏิบัติการทันที',
    coexistTip: 'ถอยออกจากพื้นที่โดยทันที ไม่มองตาโดยตรง ก้มหัวแสดงความเคารพ',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: exquisite ancient Thai royal court dress with heavy gold jewelry and very tall elaborate hairstyle adorned with flowers and gold ornaments, no visible face (face turned aside and in shadow under the tall headdress), regal upright stance with hands folded, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['palace', 'historic', 'government'], timeBonus: 0.25, nightOnly: true },
    icon: '👑',
  },

  // ── นรก ──────────────────────────────────────────────
  {
    id: 'STL-GH-024',
    nameTh: 'ผีตายทั้งกลม',
    class: 'นรก',
    rarity: 'Common',
    dangerLevel: 2,
    description: 'วิญญาณที่ตายแบบไม่มีใครรู้เห็น ต้องทนทุกข์ก่อนได้รับการปลดปล่อย',
    fieldNote: 'ลักษณะ: ร่างกลมอ้วนบวมเหมือนศพที่ถูกทอดทิ้ง เดินซมซาน ใบหน้าบวมเบ้ ปรากฏตามสถานที่เปลี่ยว\nหมายเหตุ: ระดับอันตรายต่ำ แต่อาจทำให้รู้สึกหดหู่และซึมเศร้า',
    coexistTip: 'ทำบุญอุทิศส่วนกุศล สวดมนต์ก่อนนอน อย่าอยู่คนเดียวในสถานที่เปลี่ยว',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: dark stained tattered everyday Thai clothing on a bloated swollen figure, no visible face (face swollen and bloated beyond recognition, head slightly bowed), arms hanging at sides, shambling slow posture, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['alley', 'abandoned', 'road'], timeBonus: 0.1 },
    icon: '😶',
  },
  {
    id: 'STL-GH-025',
    nameTh: 'เปรตหิวโหย',
    class: 'นรก',
    rarity: 'Uncommon',
    dangerLevel: 3,
    description: 'เปรตที่ทรมานจากความหิวโหยอย่างสุดขีด รุนแรงกว่าผีเปรตธรรมดา',
    fieldNote: 'ลักษณะ: สูงผอมแห้งอย่างสุดขีด ท้องโตขัดแย้งกับร่างผอม ตาหวำลึก ปากใหญ่พยายามกลืนกิน\nหมายเหตุ: พบบ่อยใกล้แหล่งอาหารหรือตลาด ในช่วงเข้าพรรษา',
    coexistTip: 'ตักบาตรพระให้สม่ำเสมอ อุทิศส่วนกุศลให้บรรพบุรุษ',
    inpaintingPrompt: 'A photorealistic dark silhouette: only the two extremely thin bony legs and bare feet visible in the lower half of the frame — the figure is so impossibly tall (many stories high) that the torso and head are cut off above the top edge of the photo. The skeletal legs stand like dark pillars barely wider than a human wrist, towering upward. Shreds of dark tattered cloth hang from the calves. The feet rest on the ground surface of the scene. Off-center, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['market', 'food_area', 'temple', 'road', 'park'], timeBonus: 0.15 },
    icon: '😩',
  },
  {
    id: 'STL-GH-026',
    nameTh: 'หนอนนรกปากเหล็ก',
    class: 'นรก',
    rarity: 'Rare',
    dangerLevel: 4,
    description: 'สัตว์นรกที่กัดกินวิญญาณคนบาป ปากเป็นเหล็กกล้า',
    fieldNote: 'ลักษณะ: สิ่งมีชีวิตรูปร่างประหลาดคล้ายหนอนขนาดใหญ่ ปากเป็นโลหะสีดำ เคลื่อนที่เร็วมาก ทิ้งร่องรอยไหม้บนพื้น\nหมายเหตุ: หนึ่งในสิ่งมีชีวิตจากนิรยภูมิที่อันตรายที่สุด',
    coexistTip: 'ห้ามอยู่ในพื้นที่มืดคนเดียว ห้ามทำบาปกรรมร้ายแรงในพื้นที่ศักดิ์สิทธิ์',
    inpaintingPrompt: 'A photorealistic dark creature, flat black silhouette: large grotesque serpentine creature with segmented dark body, metallic iron jaw with black metal teeth, no humanoid face (creature head with forward-facing iron maw), coiled threatening posture with head raised, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['cemetery', 'temple', 'ruin'], timeBonus: 0.25, nightOnly: true },
    icon: '🐛',
  },
  {
    id: 'STL-GH-027',
    nameTh: 'นิรยอสุรกาย',
    class: 'นรก',
    rarity: 'Legendary',
    dangerLevel: 5,
    description: 'ปีศาจนรก รูปร่างน่ากลัว ไฟลุกโชน ปรากฏตัวเฉพาะในสถานที่มีกรรมหนักสะสม',
    fieldNote: 'ลักษณะ: ร่างขนาดใหญ่กว่ามนุษย์หลายเท่า ไฟสีแดงลุกโชนรอบร่าง ตาสีแดงลุกเป็นไฟ เขี้ยวและกรงเล็บยาว กลิ่นกำมะถัน\nหมายเหตุ: ระดับอันตรายสูงสุด ห้ามเข้าใกล้ รอทีม SWAT ปฏิบัติการพิเศษ',
    coexistTip: 'ถอยออกจากพื้นที่ทันที ติดต่อส.ต.ล.ด่วน ห้ามมองตาโดยตรง',
    inpaintingPrompt: 'A photorealistic dark figure, flat black silhouette with detailed traditional Thai historical costume: massive figure twice human height in ancient dark demon ceremonial war armor with flame motifs, no visible face (deep shadow with only two red burning eyes visible), long curved black claws on both hands, dark smoke wisping at feet and shoulders, towering imposing posture, naturally present in the scene doing an everyday activity — sitting, looking around, or occupying a corner — positioned off-center in the background, unaware of the camera, as if accidentally photographed. Preserve the original photo\'s exact colors, white balance, and lighting. Blend seamlessly. Subtle 35mm film grain texture only, no color grading',
    spawnConditions: { locationTypes: ['cemetery', 'accident_site', 'ruin'], timeBonus: 0.4, nightOnly: true },
    icon: '👹',
  },
]

export const GHOST_CLASSES = {
  เร่ร่อน: { icon: '👤', description: 'วิญญาณเร่ร่อนไร้ที่อยู่', coexistTip: 'ติดตั้งแสงสว่าง หลีกเลี่ยงที่มืด' },
  ป่า: { icon: '🌿', description: 'วิญญาณสิงสถิตในป่าและต้นไม้', coexistTip: 'ขออนุญาตก่อนเข้าป่า' },
  น้ำ: { icon: '💧', description: 'วิญญาณแห่งแหล่งน้ำ', coexistTip: 'ไม่ว่ายน้ำยามดึก' },
  อาคม: { icon: '🔮', description: 'วิญญาณจากไสยศาสตร์', coexistTip: 'พกของขลัง หลีกเลี่ยงพิธีกรรม' },
  โบราณ: { icon: '🏛️', description: 'วิญญาณจากสถานที่เก่าแก่', coexistTip: 'แสดงความเคารพสถานที่' },
  ราชสำนัก: { icon: '⚔️', description: 'วิญญาณราชสำนักโบราณ', coexistTip: 'แสดงความเคารพสูงสุด' },
  นรก: { icon: '💀', description: 'วิญญาณจากนิรยภูมิ', coexistTip: 'ถอยออกทันที ติดต่อส.ต.ล.' },
}

export const GHOST_BY_ID = Object.fromEntries(GHOSTS.map((g) => [g.id, g]))
export const GHOST_BY_CLASS = GHOSTS.reduce((acc, g) => {
  if (!acc[g.class]) acc[g.class] = []
  acc[g.class].push(g)
  return acc
}, {})

export const INITIAL_PASSPORT_CLASSES = ['เร่ร่อน', 'ป่า', 'น้ำ', 'อาคม', 'โบราณ', 'ราชสำนัก']
export const RARE_CLASSES = ['อาคม', 'โบราณ', 'ราชสำนัก', 'นรก']
export const LEGENDARY_CLASSES = ['นรก']
